import * as tls from "node:tls";

// Trusts the self-signed cert generated by global-setup.ts in this worker's TLS context.
// Must run as a setupFile so every worker thread applies it before making fetch requests.
const certPem = process.env["TRUST_ANCHOR_CERT_PEM"];
if (certPem) {
  tls.setDefaultCACertificates([...tls.getCACertificates("system"), certPem]);
}
